name: tests

on:
  pull_request:
    paths-ignore:
      - .gitignore
      - CHANGELOG.md
      - CONTRIBUTING.md
      - README.md
  push:
    paths-ignore:
      - .gitignore
      - CHANGELOG.md
      - CONTRIBUTING.md
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.2'
            gemfile: gemfiles/activerecord_7.0.gemfile
          - ruby: '3.1'
            gemfile: gemfiles/activerecord_7.0.gemfile
          - ruby: '3.1'
            gemfile: gemfiles/activerecord_6.1.gemfile
          - ruby: '3.0'
            gemfile: gemfiles/activerecord_7.0.gemfile
          - ruby: '3.0'
            gemfile: gemfiles/activerecord_6.1.gemfile
          - ruby: '2.7'
            gemfile: gemfiles/activerecord_7.0.gemfile
          - ruby: '2.7'
            gemfile: gemfiles/activerecord_6.1.gemfile
          - ruby: '2.7'
            gemfile: gemfiles/activerecord_6.0.gemfile
          - ruby: '2.6'
            gemfile: gemfiles/activerecord_6.1.gemfile
          - ruby: '2.6'
            gemfile: gemfiles/activerecord_6.0.gemfile
          - ruby: '2.5'
            gemfile: gemfiles/activerecord_6.1.gemfile
          - ruby: '2.5'
            gemfile: gemfiles/activerecord_6.0.gemfile
          - ruby: '2.4'
            gemfile: gemfiles/activerecord_5.2.gemfile
          - ruby: 'jruby'
            gemfile: gemfiles/activerecord_6.1.gemfile
          - ruby: 'jruby'
            gemfile: gemfiles/activerecord_6.0.gemfile
          - ruby: 'truffleruby'
            gemfile: gemfiles/activerecord_7.0.gemfile
          - ruby: 'truffleruby'
            gemfile: gemfiles/activerecord_6.1.gemfile
          - ruby: 'truffleruby'
            gemfile: gemfiles/activerecord_6.0.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MySQL and PostgreSQL via Docker Compose
        run: docker compose up -d --wait
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: ${{ matrix.env }} bundle exec rake
